### ISSUE TITLE
Any example how to use this thing?

### ISSUE THREAD

**Issue by bill-siftlocal** [gemvein/message_train#4]
Hi,

This gem is very interesting, but I am not sure how to actually implement it.  Is there anywhere I can find examples of it use?

**Comment by nerakdon** [comment]
No demo site is available yet, but the basic idea is that if you want members of a model, such as `User`, to be able to send private messages to one another on your website, you install this gem and add it to the `User` model.  The directions on the [README](https://github.com/gemvein/message_train) describe in more detail how to set it up.
